### PR TITLE
add build/debian to support building packages for Ubuntu/Debian

### PR DESCRIPTION
**Pull request by jimmystewpot**
I have created a few files to facilitate people building the Concurrency-Kit libraries for Ubuntu/Debian. I hope that this helps other users.

### CODE REVIEW

**Comment by sbahra** [comment]
Thanks for the patch Jimmy. This is terrific, thanks! How are these expected to be used (I'm unfamiliar with dpkg)?

**Comment by jimmystewpot** [comment]
I will update a debian/ubuntu readme so that it makes life easier for everyone.. stay tuned.

**Comment by jimmystewpot** [comment]
I have created a README to help people follow how to build debian or ubuntu packages.

The build files are all setup to only build with 0.x version numbers. I have done it this way so that as versions progress developers can have multiple versions of the files installed without causing problems. I generally find that fairly sane in my dev environment however everyone is slightly different. Keen for feedback on that point..

**Comment by sbahra** [comment]
Thanks! I will read over this tomorrow night (EST).

**Comment by sbahra** [comment]
Hey Jimmy, thanks for this! It seems like the best bet is to maintain this within the Debian repository. Doesn't seem idiomatic to put this inside of the upstream repository.

**Pull request closed without merging**
